#!/bin/bash

options=()
parameters=()
fl=false

for arg in "$@"
do
  if [ "$arg" == "--" ]; then
    fl=true
  elif $fl; then
	parameters+=("$arg")
  elif [[ "$arg" == -* ]]; then
    options+=("$arg")
  else
    parameters+=("$arg")
  fi
done

echo "options:"
for option in "${options[@]}"
do
    echo "$option"
done

echo "parameters:"
for parameter in "${parameters[@]}"
do
    echo "$parameter"
done
